# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.api.launchpad_api import LaunchpadApi  # noqa: E501
from paycomet-client.rest import ApiException


class TestLaunchpadApi(unittest.TestCase):
    """LaunchpadApi unit test stubs"""

    def setUp(self):
        self.api = LaunchpadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_launch_authorization(self):
        """Test case for launch_authorization

        Creates a payment link and sends it to customer  # noqa: E501
        """
        pass

    def test_launch_preauthorization(self):
        """Test case for launch_preauthorization

        Executes a preauthorization link and sends it to customer  # noqa: E501
        """
        pass

    def test_launch_subscription(self):
        """Test case for launch_subscription

        Creates a subscription link and sends it to customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
