# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.v1_cards_body import V1CardsBody  # noqa: E501
from paycomet-client.rest import ApiException


class TestV1CardsBody(unittest.TestCase):
    """V1CardsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1CardsBody(self):
        """Test V1CardsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.v1_cards_body.V1CardsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
