# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet_client
from paycomet_client.models.inline_response20027_submerchant import InlineResponse20027Submerchant  # noqa: E501
from paycomet_client.rest import ApiException


class TestInlineResponse20027Submerchant(unittest.TestCase):
    """InlineResponse20027Submerchant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20027Submerchant(self):
        """Test InlineResponse20027Submerchant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet_client.models.inline_response20027_submerchant.InlineResponse20027Submerchant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
