# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet_client
from paycomet_client.models.inline_response20028_submerchant import InlineResponse20028Submerchant  # noqa: E501
from paycomet_client.rest import ApiException


class TestInlineResponse20028Submerchant(unittest.TestCase):
    """InlineResponse20028Submerchant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028Submerchant(self):
        """Test InlineResponse20028Submerchant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet_client.models.inline_response20028_submerchant.InlineResponse20028Submerchant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
