# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.v1form_payment_merchant_data_billing import V1formPaymentMerchantDataBilling  # noqa: E501
from paycomet-client.rest import ApiException


class TestV1formPaymentMerchantDataBilling(unittest.TestCase):
    """V1formPaymentMerchantDataBilling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1formPaymentMerchantDataBilling(self):
        """Test V1formPaymentMerchantDataBilling"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.v1form_payment_merchant_data_billing.V1formPaymentMerchantDataBilling()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
