# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.inline_response20029 import InlineResponse20029  # noqa: E501
from paycomet-client.rest import ApiException


class TestInlineResponse20029(unittest.TestCase):
    """InlineResponse20029 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20029(self):
        """Test InlineResponse20029"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.inline_response20029.InlineResponse20029()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
