# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.inline_response4224_error import InlineResponse4224Error  # noqa: E501
from paycomet-client.rest import ApiException


class TestInlineResponse4224Error(unittest.TestCase):
    """InlineResponse4224Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4224Error(self):
        """Test InlineResponse4224Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.inline_response4224_error.InlineResponse4224Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
