# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.inline_response20033 import InlineResponse20033  # noqa: E501
from paycomet-client.rest import ApiException


class TestInlineResponse20033(unittest.TestCase):
    """InlineResponse20033 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20033(self):
        """Test InlineResponse20033"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.inline_response20033.InlineResponse20033()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
