# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.v1_heartbeat_body import V1HeartbeatBody  # noqa: E501
from paycomet-client.rest import ApiException


class TestV1HeartbeatBody(unittest.TestCase):
    """V1HeartbeatBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1HeartbeatBody(self):
        """Test V1HeartbeatBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.v1_heartbeat_body.V1HeartbeatBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
