# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet_client
from paycomet_client.models.inline_response4222_error import InlineResponse4222Error  # noqa: E501
from paycomet_client.rest import ApiException


class TestInlineResponse4222Error(unittest.TestCase):
    """InlineResponse4222Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4222Error(self):
        """Test InlineResponse4222Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet_client.models.inline_response4222_error.InlineResponse4222Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
