# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet_client
from paycomet_client.api.error_api import ErrorApi  # noqa: E501
from paycomet_client.rest import ApiException


class TestErrorApi(unittest.TestCase):
    """ErrorApi unit test stubs"""

    def setUp(self):
        self.api = ErrorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_error(self):
        """Test case for info_error

        Gets an error description  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
