# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import paycomet-client
from paycomet-client.models.order_refund_body import OrderRefundBody  # noqa: E501
from paycomet-client.rest import ApiException


class TestOrderRefundBody(unittest.TestCase):
    """OrderRefundBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderRefundBody(self):
        """Test OrderRefundBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = paycomet-client.models.order_refund_body.OrderRefundBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
