# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from paycomet_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_ERRORS = "/v1/errors"
    V1_CARDS = "/v1/cards"
    V1_CARDS_INFO = "/v1/cards/info"
    V1_CARDS_DELETE = "/v1/cards/delete"
    V1_CARDS_EDIT = "/v1/cards/edit"
    V1_CARDS_PHYSICAL = "/v1/cards/physical"
    V1_CARDS_PHYSICAL_EDIT = "/v1/cards/physical/edit"
    V1_BALANCE = "/v1/balance"
    V1_EXCHANGE = "/v1/exchange"
    V1_HEARTBEAT = "/v1/heartbeat"
    V1_INVOICES = "/v1/invoices"
    V1_IP = "/v1/ip"
    V1_IP_REMOTE = "/v1/ip/remote"
    V1_METHODS = "/v1/methods"
    V1_FORM = "/v1/form"
    V1_PAYMENTS = "/v1/payments"
    V1_PAYMENTS_ORDER_REFUND = "/v1/payments/{order}/refund"
    V1_PAYMENTS_ORDER_INFO = "/v1/payments/{order}/info"
    V1_PAYMENTS_SEARCH = "/v1/payments/search"
    V1_PAYMENTS_PREAUTH = "/v1/payments/preauth"
    V1_PAYMENTS_ORDER_PREAUTH_CANCEL = "/v1/payments/{order}/preauth/cancel"
    V1_PAYMENTS_ORDER_PREAUTH_CONFIRM = "/v1/payments/{order}/preauth/confirm"
    V1_PAYMENTS_RTOKEN = "/v1/payments/rtoken"
    V1_PAYMENTS_PREAUTHRTOKEN = "/v1/payments/preauthrtoken"
    V1_SUBSCRIPTION = "/v1/subscription"
    V1_SUBSCRIPTION_ORDER_EDIT = "/v1/subscription/{order}/edit"
    V1_SUBSCRIPTION_ORDER_REMOVE = "/v1/subscription/{order}/remove"
    V1_SUBSCRIPTION_ORDER_INFO = "/v1/subscription/{order}/info"
    V1_PAYMENTS_DCC = "/v1/payments/dcc"
    V1_PAYMENTS_ORDER_DCC_CONFIRM = "/v1/payments/{order}/dcc/confirm"
    V1_MARKETPLACE_SPLITTRANSFER = "/v1/marketplace/split-transfer"
    V1_MARKETPLACE_SPLITTRANSFERREVERSAL = "/v1/marketplace/split-transfer-reversal"
    V1_MARKETPLACE_TRANSFER = "/v1/marketplace/transfer"
    V1_MARKETPLACE_TRANSFERREVERSAL = "/v1/marketplace/transfer-reversal"
    V1_SEPA_ADDDOCUMENT = "/v1/sepa/add-document"
    V1_SEPA_ENROLECUSTOMER = "/v1/sepa/enrole-customer"
    V1_SEPA_CHECKDOCUMENT = "/v1/sepa/check-document"
    V1_SEPA_CHECKCUSTOMER = "/v1/sepa/check-customer"
    V1_SEPA_OPERATIONS = "/v1/sepa/operations"
    V1_SEPA_CANCEL = "/v1/sepa/cancel"
    V1_IVR_GETSESSION = "/v1/ivr/get-session"
    V1_IVR_SESSIONSTATE = "/v1/ivr/session-state"
    V1_IVR_SESSIONCANCEL = "/v1/ivr/session-cancel"
    V1_LAUNCHPAD_AUTHORIZATION = "/v1/launchpad/authorization"
    V1_LAUNCHPAD_PREAUTHORIZATION = "/v1/launchpad/preauthorization"
    V1_LAUNCHPAD_SUBSCRIPTION = "/v1/launchpad/subscription"
    V1_TOKEN = "/v1/token"
