# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    The version of the OpenAPI document: 2.78.0
    Contact: tecnico@paycomet.com
    Generated by: https://openapi-generator.tech
"""

from paycomet_client.paths.v1_ivr_session_state.post import CheckSession
from paycomet_client.paths.v1_ivr_get_session.post import GetSession
from paycomet_client.paths.v1_ivr_session_cancel.post import SessionCancel


class IVRApi(
    CheckSession,
    GetSession,
    SessionCancel,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
