# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    The version of the OpenAPI document: 2.78.0
    Contact: tecnico@paycomet.com
    Generated by: https://openapi-generator.tech
"""

from paycomet_client.paths.v1_marketplace_split_transfer.post import SplitTransfer
from paycomet_client.paths.v1_marketplace_split_transfer_reversal.post import SplitTransferReversal
from paycomet_client.paths.v1_marketplace_transfer.post import Transfer
from paycomet_client.paths.v1_marketplace_transfer_reversal.post import TransferReversal


class MarketplaceApi(
    SplitTransfer,
    SplitTransferReversal,
    Transfer,
    TransferReversal,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
