# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    The version of the OpenAPI document: 2.78.0
    Contact: tecnico@paycomet.com
    Generated by: https://openapi-generator.tech
"""

from paycomet_client.paths.v1_subscription.post import CreateSubscription
from paycomet_client.paths.v1_subscription_order_edit.post import EditSubscription
from paycomet_client.paths.v1_subscription_order_info.post import InfoSubscription
from paycomet_client.paths.v1_subscription_order_remove.post import RemoveSubscription


class SusbcriptionsApi(
    CreateSubscription,
    EditSubscription,
    InfoSubscription,
    RemoveSubscription,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
