# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20019(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'str',
        'order': 'str',
        'amount': 'str',
        'error_code': 'int',
        'card_country': 'str'
    }

    attribute_map = {
        'currency': 'currency',
        'order': 'order',
        'amount': 'amount',
        'error_code': 'errorCode',
        'card_country': 'cardCountry'
    }

    def __init__(self, currency=None, order=None, amount=None, error_code=None, card_country=None):  # noqa: E501
        """InlineResponse20019 - a model defined in Swagger"""  # noqa: E501
        self._currency = None
        self._order = None
        self._amount = None
        self._error_code = None
        self._card_country = None
        self.discriminator = None
        if currency is not None:
            self.currency = currency
        if order is not None:
            self.order = order
        if amount is not None:
            self.amount = amount
        if error_code is not None:
            self.error_code = error_code
        if card_country is not None:
            self.card_country = card_country

    @property
    def currency(self):
        """Gets the currency of this InlineResponse20019.  # noqa: E501


        :return: The currency of this InlineResponse20019.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this InlineResponse20019.


        :param currency: The currency of this InlineResponse20019.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def order(self):
        """Gets the order of this InlineResponse20019.  # noqa: E501


        :return: The order of this InlineResponse20019.  # noqa: E501
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this InlineResponse20019.


        :param order: The order of this InlineResponse20019.  # noqa: E501
        :type: str
        """

        self._order = order

    @property
    def amount(self):
        """Gets the amount of this InlineResponse20019.  # noqa: E501


        :return: The amount of this InlineResponse20019.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InlineResponse20019.


        :param amount: The amount of this InlineResponse20019.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def error_code(self):
        """Gets the error_code of this InlineResponse20019.  # noqa: E501


        :return: The error_code of this InlineResponse20019.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this InlineResponse20019.


        :param error_code: The error_code of this InlineResponse20019.  # noqa: E501
        :type: int
        """

        self._error_code = error_code

    @property
    def card_country(self):
        """Gets the card_country of this InlineResponse20019.  # noqa: E501


        :return: The card_country of this InlineResponse20019.  # noqa: E501
        :rtype: str
        """
        return self._card_country

    @card_country.setter
    def card_country(self, card_country):
        """Sets the card_country of this InlineResponse20019.


        :param card_country: The card_country of this InlineResponse20019.  # noqa: E501
        :type: str
        """

        self._card_country = card_country

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20019, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20019):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
