# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1ErrorsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'terminal': 'int',
        'error_code': 'int',
        'lang': 'str'
    }

    attribute_map = {
        'terminal': 'terminal',
        'error_code': 'errorCode',
        'lang': 'lang'
    }

    def __init__(self, terminal=None, error_code=None, lang='es'):  # noqa: E501
        """V1ErrorsBody - a model defined in Swagger"""  # noqa: E501
        self._terminal = None
        self._error_code = None
        self._lang = None
        self.discriminator = None
        self.terminal = terminal
        self.error_code = error_code
        if lang is not None:
            self.lang = lang

    @property
    def terminal(self):
        """Gets the terminal of this V1ErrorsBody.  # noqa: E501

        Product or terminal Id.  # noqa: E501

        :return: The terminal of this V1ErrorsBody.  # noqa: E501
        :rtype: int
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this V1ErrorsBody.

        Product or terminal Id.  # noqa: E501

        :param terminal: The terminal of this V1ErrorsBody.  # noqa: E501
        :type: int
        """
        if terminal is None:
            raise ValueError("Invalid value for `terminal`, must not be `None`")  # noqa: E501

        self._terminal = terminal

    @property
    def error_code(self):
        """Gets the error_code of this V1ErrorsBody.  # noqa: E501

        Error code given by PAYCOMET.  # noqa: E501

        :return: The error_code of this V1ErrorsBody.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this V1ErrorsBody.

        Error code given by PAYCOMET.  # noqa: E501

        :param error_code: The error_code of this V1ErrorsBody.  # noqa: E501
        :type: int
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def lang(self):
        """Gets the lang of this V1ErrorsBody.  # noqa: E501

        ISO2 code of language.  # noqa: E501

        :return: The lang of this V1ErrorsBody.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this V1ErrorsBody.

        ISO2 code of language.  # noqa: E501

        :param lang: The lang of this V1ErrorsBody.  # noqa: E501
        :type: str
        """

        self._lang = lang

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ErrorsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ErrorsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
