# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1paymentsorderpreauthconfirmPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'terminal': 'int',
        'amount': 'str',
        'original_ip': 'str',
        'auth_code': 'str',
        'deferred': 'int',
        'notify_direct_payment': 'int'
    }

    attribute_map = {
        'terminal': 'terminal',
        'amount': 'amount',
        'original_ip': 'originalIp',
        'auth_code': 'authCode',
        'deferred': 'deferred',
        'notify_direct_payment': 'notifyDirectPayment'
    }

    def __init__(self, terminal=None, amount=None, original_ip=None, auth_code=None, deferred=0, notify_direct_payment=None):  # noqa: E501
        """V1paymentsorderpreauthconfirmPayment - a model defined in Swagger"""  # noqa: E501
        self._terminal = None
        self._amount = None
        self._original_ip = None
        self._auth_code = None
        self._deferred = None
        self._notify_direct_payment = None
        self.discriminator = None
        self.terminal = terminal
        self.amount = amount
        self.original_ip = original_ip
        self.auth_code = auth_code
        if deferred is not None:
            self.deferred = deferred
        if notify_direct_payment is not None:
            self.notify_direct_payment = notify_direct_payment

    @property
    def terminal(self):
        """Gets the terminal of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501

        Product or terminal Id.  # noqa: E501

        :return: The terminal of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :rtype: int
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this V1paymentsorderpreauthconfirmPayment.

        Product or terminal Id.  # noqa: E501

        :param terminal: The terminal of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :type: int
        """
        if terminal is None:
            raise ValueError("Invalid value for `terminal`, must not be `None`")  # noqa: E501

        self._terminal = terminal

    @property
    def amount(self):
        """Gets the amount of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501


        :return: The amount of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this V1paymentsorderpreauthconfirmPayment.


        :param amount: The amount of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :type: str
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def original_ip(self):
        """Gets the original_ip of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501


        :return: The original_ip of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :rtype: str
        """
        return self._original_ip

    @original_ip.setter
    def original_ip(self, original_ip):
        """Sets the original_ip of this V1paymentsorderpreauthconfirmPayment.


        :param original_ip: The original_ip of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :type: str
        """
        if original_ip is None:
            raise ValueError("Invalid value for `original_ip`, must not be `None`")  # noqa: E501

        self._original_ip = original_ip

    @property
    def auth_code(self):
        """Gets the auth_code of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501

        Authorization bank code of the transaction (required to execute a return).  # noqa: E501

        :return: The auth_code of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :rtype: str
        """
        return self._auth_code

    @auth_code.setter
    def auth_code(self, auth_code):
        """Sets the auth_code of this V1paymentsorderpreauthconfirmPayment.

        Authorization bank code of the transaction (required to execute a return).  # noqa: E501

        :param auth_code: The auth_code of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :type: str
        """
        if auth_code is None:
            raise ValueError("Invalid value for `auth_code`, must not be `None`")  # noqa: E501

        self._auth_code = auth_code

    @property
    def deferred(self):
        """Gets the deferred of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501

        Identify the preauthorization as deferred  # noqa: E501

        :return: The deferred of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :rtype: int
        """
        return self._deferred

    @deferred.setter
    def deferred(self, deferred):
        """Sets the deferred of this V1paymentsorderpreauthconfirmPayment.

        Identify the preauthorization as deferred  # noqa: E501

        :param deferred: The deferred of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :type: int
        """

        self._deferred = deferred

    @property
    def notify_direct_payment(self):
        """Gets the notify_direct_payment of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501

        Configurate POST notification of the operation result (possible values: 1 - force notify, 2 - not notify). It will notify if is not informed  # noqa: E501

        :return: The notify_direct_payment of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :rtype: int
        """
        return self._notify_direct_payment

    @notify_direct_payment.setter
    def notify_direct_payment(self, notify_direct_payment):
        """Sets the notify_direct_payment of this V1paymentsorderpreauthconfirmPayment.

        Configurate POST notification of the operation result (possible values: 1 - force notify, 2 - not notify). It will notify if is not informed  # noqa: E501

        :param notify_direct_payment: The notify_direct_payment of this V1paymentsorderpreauthconfirmPayment.  # noqa: E501
        :type: int
        """

        self._notify_direct_payment = notify_direct_payment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1paymentsorderpreauthconfirmPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1paymentsorderpreauthconfirmPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
