# coding: utf-8

# flake8: noqa

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    The version of the OpenAPI document: 2.78.0
    Contact: tecnico@paycomet.com
    Generated by: https://openapi-generator.tech
"""

__version__ = "2.78.0"

# import ApiClient
from paycomet_client.api_client import ApiClient

# import Configuration
from paycomet_client.configuration import Configuration

# import exceptions
from paycomet_client.exceptions import OpenApiException
from paycomet_client.exceptions import ApiAttributeError
from paycomet_client.exceptions import ApiTypeError
from paycomet_client.exceptions import ApiValueError
from paycomet_client.exceptions import ApiKeyError
from paycomet_client.exceptions import ApiException
