# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CardsEditBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'terminal': 'int',
        'id_user': 'int',
        'token_user': 'str',
        'cvc2': 'str',
        'expiry_year': 'str',
        'expiry_month': 'str'
    }

    attribute_map = {
        'terminal': 'terminal',
        'id_user': 'idUser',
        'token_user': 'tokenUser',
        'cvc2': 'cvc2',
        'expiry_year': 'expiryYear',
        'expiry_month': 'expiryMonth'
    }

    def __init__(self, terminal=None, id_user=None, token_user=None, cvc2=None, expiry_year=None, expiry_month=None):  # noqa: E501
        """CardsEditBody - a model defined in Swagger"""  # noqa: E501
        self._terminal = None
        self._id_user = None
        self._token_user = None
        self._cvc2 = None
        self._expiry_year = None
        self._expiry_month = None
        self.discriminator = None
        self.terminal = terminal
        self.id_user = id_user
        self.token_user = token_user
        if cvc2 is not None:
            self.cvc2 = cvc2
        self.expiry_year = expiry_year
        self.expiry_month = expiry_month

    @property
    def terminal(self):
        """Gets the terminal of this CardsEditBody.  # noqa: E501

        Product or terminal Id.  # noqa: E501

        :return: The terminal of this CardsEditBody.  # noqa: E501
        :rtype: int
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this CardsEditBody.

        Product or terminal Id.  # noqa: E501

        :param terminal: The terminal of this CardsEditBody.  # noqa: E501
        :type: int
        """
        if terminal is None:
            raise ValueError("Invalid value for `terminal`, must not be `None`")  # noqa: E501

        self._terminal = terminal

    @property
    def id_user(self):
        """Gets the id_user of this CardsEditBody.  # noqa: E501

        Identification of user card given by PAYCOMET. Mandatory if is a card payment.  # noqa: E501

        :return: The id_user of this CardsEditBody.  # noqa: E501
        :rtype: int
        """
        return self._id_user

    @id_user.setter
    def id_user(self, id_user):
        """Sets the id_user of this CardsEditBody.

        Identification of user card given by PAYCOMET. Mandatory if is a card payment.  # noqa: E501

        :param id_user: The id_user of this CardsEditBody.  # noqa: E501
        :type: int
        """
        if id_user is None:
            raise ValueError("Invalid value for `id_user`, must not be `None`")  # noqa: E501

        self._id_user = id_user

    @property
    def token_user(self):
        """Gets the token_user of this CardsEditBody.  # noqa: E501

        Identification of user card given by PAYCOMET. Mandatory if is a card payment.  # noqa: E501

        :return: The token_user of this CardsEditBody.  # noqa: E501
        :rtype: str
        """
        return self._token_user

    @token_user.setter
    def token_user(self, token_user):
        """Sets the token_user of this CardsEditBody.

        Identification of user card given by PAYCOMET. Mandatory if is a card payment.  # noqa: E501

        :param token_user: The token_user of this CardsEditBody.  # noqa: E501
        :type: str
        """
        if token_user is None:
            raise ValueError("Invalid value for `token_user`, must not be `None`")  # noqa: E501

        self._token_user = token_user

    @property
    def cvc2(self):
        """Gets the cvc2 of this CardsEditBody.  # noqa: E501

        cvc2. Mandatory if no JetToken provided  # noqa: E501

        :return: The cvc2 of this CardsEditBody.  # noqa: E501
        :rtype: str
        """
        return self._cvc2

    @cvc2.setter
    def cvc2(self, cvc2):
        """Sets the cvc2 of this CardsEditBody.

        cvc2. Mandatory if no JetToken provided  # noqa: E501

        :param cvc2: The cvc2 of this CardsEditBody.  # noqa: E501
        :type: str
        """

        self._cvc2 = cvc2

    @property
    def expiry_year(self):
        """Gets the expiry_year of this CardsEditBody.  # noqa: E501

        Expiry year.   Mandatory if no JetToken provided.  # noqa: E501

        :return: The expiry_year of this CardsEditBody.  # noqa: E501
        :rtype: str
        """
        return self._expiry_year

    @expiry_year.setter
    def expiry_year(self, expiry_year):
        """Sets the expiry_year of this CardsEditBody.

        Expiry year.   Mandatory if no JetToken provided.  # noqa: E501

        :param expiry_year: The expiry_year of this CardsEditBody.  # noqa: E501
        :type: str
        """
        if expiry_year is None:
            raise ValueError("Invalid value for `expiry_year`, must not be `None`")  # noqa: E501

        self._expiry_year = expiry_year

    @property
    def expiry_month(self):
        """Gets the expiry_month of this CardsEditBody.  # noqa: E501

        Expiry month.  Mandatory if no JetToken provided.  # noqa: E501

        :return: The expiry_month of this CardsEditBody.  # noqa: E501
        :rtype: str
        """
        return self._expiry_month

    @expiry_month.setter
    def expiry_month(self, expiry_month):
        """Sets the expiry_month of this CardsEditBody.

        Expiry month.  Mandatory if no JetToken provided.  # noqa: E501

        :param expiry_month: The expiry_month of this CardsEditBody.  # noqa: E501
        :type: str
        """
        if expiry_month is None:
            raise ValueError("Invalid value for `expiry_month`, must not be `None`")  # noqa: E501

        self._expiry_month = expiry_month

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CardsEditBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CardsEditBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
