# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.99.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1invoicesPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'terminal': 'int',
        'shops_ids': 'list[int]',
        'invoices_ids': 'list[int]',
        'from_date': 'str',
        'to_date': 'str'
    }

    attribute_map = {
        'terminal': 'terminal',
        'shops_ids': 'shopsIds',
        'invoices_ids': 'invoicesIds',
        'from_date': 'fromDate',
        'to_date': 'toDate'
    }

    def __init__(self, terminal=None, shops_ids=None, invoices_ids=None, from_date=None, to_date=None):  # noqa: E501
        """V1invoicesPayment - a model defined in Swagger"""  # noqa: E501
        self._terminal = None
        self._shops_ids = None
        self._invoices_ids = None
        self._from_date = None
        self._to_date = None
        self.discriminator = None
        self.terminal = terminal
        self.shops_ids = shops_ids
        if invoices_ids is not None:
            self.invoices_ids = invoices_ids
        self.from_date = from_date
        self.to_date = to_date

    @property
    def terminal(self):
        """Gets the terminal of this V1invoicesPayment.  # noqa: E501

        Product or terminal Id.  # noqa: E501

        :return: The terminal of this V1invoicesPayment.  # noqa: E501
        :rtype: int
        """
        return self._terminal

    @terminal.setter
    def terminal(self, terminal):
        """Sets the terminal of this V1invoicesPayment.

        Product or terminal Id.  # noqa: E501

        :param terminal: The terminal of this V1invoicesPayment.  # noqa: E501
        :type: int
        """
        if terminal is None:
            raise ValueError("Invalid value for `terminal`, must not be `None`")  # noqa: E501

        self._terminal = terminal

    @property
    def shops_ids(self):
        """Gets the shops_ids of this V1invoicesPayment.  # noqa: E501


        :return: The shops_ids of this V1invoicesPayment.  # noqa: E501
        :rtype: list[int]
        """
        return self._shops_ids

    @shops_ids.setter
    def shops_ids(self, shops_ids):
        """Sets the shops_ids of this V1invoicesPayment.


        :param shops_ids: The shops_ids of this V1invoicesPayment.  # noqa: E501
        :type: list[int]
        """
        if shops_ids is None:
            raise ValueError("Invalid value for `shops_ids`, must not be `None`")  # noqa: E501

        self._shops_ids = shops_ids

    @property
    def invoices_ids(self):
        """Gets the invoices_ids of this V1invoicesPayment.  # noqa: E501


        :return: The invoices_ids of this V1invoicesPayment.  # noqa: E501
        :rtype: list[int]
        """
        return self._invoices_ids

    @invoices_ids.setter
    def invoices_ids(self, invoices_ids):
        """Sets the invoices_ids of this V1invoicesPayment.


        :param invoices_ids: The invoices_ids of this V1invoicesPayment.  # noqa: E501
        :type: list[int]
        """

        self._invoices_ids = invoices_ids

    @property
    def from_date(self):
        """Gets the from_date of this V1invoicesPayment.  # noqa: E501

        Start datetime limit (format: YmdHis)  # noqa: E501

        :return: The from_date of this V1invoicesPayment.  # noqa: E501
        :rtype: str
        """
        return self._from_date

    @from_date.setter
    def from_date(self, from_date):
        """Sets the from_date of this V1invoicesPayment.

        Start datetime limit (format: YmdHis)  # noqa: E501

        :param from_date: The from_date of this V1invoicesPayment.  # noqa: E501
        :type: str
        """
        if from_date is None:
            raise ValueError("Invalid value for `from_date`, must not be `None`")  # noqa: E501

        self._from_date = from_date

    @property
    def to_date(self):
        """Gets the to_date of this V1invoicesPayment.  # noqa: E501

        Finish datetime limit (format: YmdHis)  # noqa: E501

        :return: The to_date of this V1invoicesPayment.  # noqa: E501
        :rtype: str
        """
        return self._to_date

    @to_date.setter
    def to_date(self, to_date):
        """Sets the to_date of this V1invoicesPayment.

        Finish datetime limit (format: YmdHis)  # noqa: E501

        :param to_date: The to_date of this V1invoicesPayment.  # noqa: E501
        :type: str
        """
        if to_date is None:
            raise ValueError("Invalid value for `to_date`, must not be `None`")  # noqa: E501

        self._to_date = to_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1invoicesPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1invoicesPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
